# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/startdde.spec

# add or remove files that should be synced
synced_files:
    - rpm/startdde.spec
    - .packit.yaml

upstream_package_name: startdde
# downstream (Fedora) RPM package name
downstream_package_name: startdde

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"0,/Version:/ s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/startdde.spec"
